# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hVo6-nraQeGWmI3HVop9PsLObk_1pYP
"""

[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#1F2937"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

import os
import toml

# Configurações
config = {
    "theme": {
        "primaryColor": "#1E3A8A",
        "backgroundColor": "#FFFFFF",
        "secondaryBackgroundColor": "#F3F4F6",
        "textColor": "#1F2937",
        "font": "sans serif"
    },
    "server": {
        "maxUploadSize": 50,
        "enableXsrfProtection": True,
        "enableCORS": False
    },
    "browser": {
        "gatherUsageStats": False
    }
}

# Criar pasta e arquivo
os.makedirs(".streamlit", exist_ok=True)
with open(".streamlit/config.toml", "w") as f:
    toml.dump(config, f)

print("✅ Arquivo .streamlit/config.toml criado com sucesso!")